---
- hosts: localhost

  tasks:
    - name: Install CLI apps with Homebrew
      homebrew: name={{ item }} state=present
      with_items:
         - mackup
         - rbenv
         - ruby-build
         - mysql
         - gpg
         - tmux
         - vim

    - name: Install CLI apps with Homebrew install options
      homebrew: name={{ item.name }} state=present install_options={{ item.options }}
      with_items:
         # Needed to copy/paste to system clipboard in tmux+VIM.
         # You also need to add a line in the .tmux.config (see https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard)
         # Mine is in my dotfiles
         - {name: reattach-to-user-namespace, options: with-wrap-pbcopy-and-pbpaste}

    - name: Install OSX apps with Cask
      homebrew_cask: name={{ item }} state=present
      with_items:
         - alfred
         - bettertouchtool
         - clipmenu
         - dropbox
         - firefox
         - filezilla
         - github-desktop
         - google-chrome
         - iterm2
         - licecap
         - mplayerx
         - selfcontrol
         - skype
         - sequel-pro
         - sublime-text
         - vlc
         - karabiner
         - karabiner-elements
         - virtualbox
         - vagrant

    - name: Install Sublime plugins
      git: repo=ssh://git@github.com/{{ item.name }}.git dest="~/Library/Application Support/Sublime Text/{{ item.source }}"
      with_items:
         - {name: SideBarEnhancements,        source: titoBouzout/SideBarEnhancements}
         - {name: GitHubinator,               source: ehamiter/ST2-GitHubinator}
         - {name: Shell-Turtlestein,          source: misfo/Shell-Turtlestein}
         - {name: ExpandSelectionByParagraph, source: natew/ExpandSelectionByParagraph}
         - {name: stringutilities,            source: akalongman/sublimetext-stringutilities}
         - {name: ChangeQuotes,               source: colinta/SublimeChangeQuotes}
         - {name: Puppet,                     source: russCloak/SublimePuppet}
         - {name: Stylus,                     source: billymoon/Stylus}
         - {name: Sass,                       source: nathos/sass-textmate-bundle}
         - {name: Jade,                       source: davidrios/jade-tmbundle}
         - {name: HAML,                       source: phuibonhoa/handcrafted-haml-textmate-bundle}
         - {name: Better CoffeeScript,        source: aponxi/sublime-better-coffeescript}
         - {name: SSH Config,                 source: robballou/sublimetext-sshconfig}
         - {name: Cucumber,                   source: ejoubaud/cucumber-sublime-bundle} # TODO: Revert to original when tmerge the st3 branch to master, or when Boxen repository supports branch
         - {name: cucumber-step-finder,       source: danielfrey/sublime-cucumber-step-finder }
